"""add soft delete to movies

Revision ID: e8b9bdf5fa41
Revises: a8cab6b41aff
Create Date: 2026-05-06 15:13:47.415604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b9bdf5fa41'
down_revision: Union[str, Sequence[str], None] = 'a8cab6b41aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_id'), table_name='movie')
    op.drop_index(op.f('ix_movie_imdb_id'), table_name='movie')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_table('movie')
    op.add_column('movies', sa.Column('plots', sa.String(), nullable=True))
    op.drop_column('movies', 'plot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('plot', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('movies', 'plots')
    op.create_table('movie',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('director', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('imdb_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('poster', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plot', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('movie_pkey'))
    )
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=True)
    op.create_index(op.f('ix_movie_imdb_id'), 'movie', ['imdb_id'], unique=True)
    op.create_index(op.f('ix_movie_id'), 'movie', ['id'], unique=False)
    # ### end Alembic commands ###
