"""rename plots to plot

Revision ID: e8d5e2398e5a
Revises: e8b9bdf5fa41
Create Date: 2026-05-06 15:16:24.608892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d5e2398e5a'
down_revision: Union[str, Sequence[str], None] = 'e8b9bdf5fa41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
