import os
from dotenv import load_dotenv
from sqlalchemy import engine_from_config, pool
from alembic import context

# 👇 Cargar variables de entorno
load_dotenv()

config = context.config

# 👇 Sobrescribir la URL de alembic.ini
DATABASE_URL = os.getenv("DATABASE_URL")
config.set_main_option("sqlalchemy.url", DATABASE_URL)